spring:
  profiles: peer1

server:
  port: 8001

eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
        #设置与Eureka Server交互的地址，多个地址可用，使用逗号分隔
        #双节点的注册中心的搭建，将eureka1的serviceUrl指向eureka2
        defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/
